"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
from setuptools import setup

APP = ['main_widget.py']

img_files = []
txt_files = []
imgs_base_dir = './imgs'
txt_base_dir = './files'

for fname in os.listdir(imgs_base_dir):
    if fname.split('.')[-1] == 'png':
        full_name = os.path.join(imgs_base_dir, fname)
        img_files.append(full_name)

for fname in os.listdir(txt_base_dir):
    full_name = os.path.join(txt_base_dir, fname)
    txt_files.append(full_name)

DATA_FILES = [('imgs', img_files), ('files', txt_files), ('records', [])]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
